### ISSUE TITLE
I2 column name bug needs fixing - should be easy

### ISSUE THREAD

**Issue by daniel1noble** [daniel1noble/metaAidR#6]
if(phylo == FALSE){
		  	## FIXED PROBLEM WITH COLUMN NAMES in I2
		  	tmpMatrix <- Matrix::cBind(I2_re[,-match("obs", colnames(I2_re))], I2_total)
		  		colnames(tmpMatrix) <- c(colnames(I2_re)[-match("obs", colnames(I2_re))], "total")

Problem arises when fewer random effects in model (i.e. just single random effect) which turns I2_re into a vector without column header. Which creates issues. Also, some additional problems when only one random effect is included that needs more carful exploration. Maybe that model fit changes with only one level.

**Comment by daniel1noble** [comment]
OK. I think I tracked problem here. Seems to be a matrix binding problem. To fix all tmpMatrix objects need coerced to dataframes:
tmpMatrix <- as.data.frame(Matrix::cBind(I2_re[,-match("obs", colnames(I2_re))], I2_total)
colnames(tmpMatrix) <- c(colnames(I2_re)[-match("obs", colnames(I2_re))], "total"))

**Comment by thomased** [comment]
Pretty sure this one was fixed in that little PR of mine you merged (here - https://github.com/daniel1noble/metaAidR/pull/14/commits/100e55f68725edbd349027aa3c0900ac2995279b#). I meant to open a separate PR for it but accidentally pushed it to the same one ages ago, then just...forgot to correct it.

Anyway, should be fixed!

**Comment by daniel1noble** [comment]
Thanks buddy!
